// <auto-generated />
using System;
using HW_Academy_RazorPages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HW_Academy_RazorPages.Migrations
{
    [DbContext(typeof(HW_Academy_RazorPagesContext))]
    partial class HW_Academy_RazorPagesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HW_Academy_RazorPages.Models.Direction", b =>
                {
                    b.Property<byte>("direction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("direction_id"));

                    b.Property<string>("direction_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("direction_id");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("HW_Academy_RazorPages.Models.Discipline", b =>
                {
                    b.Property<short>("discipline_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("discipline_id"));

                    b.Property<string>("discipline_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("number_of_lessons")
                        .HasColumnType("TINYINT");

                    b.HasKey("discipline_id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("HW_Academy_RazorPages.Models.Group", b =>
                {
                    b.Property<int>("group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("group_id"));

                    b.Property<byte>("direction")
                        .HasColumnType("tinyint");

                    b.Property<string>("group_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("learning_days")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("start_time")
                        .HasColumnType("time");

                    b.HasKey("group_id");

                    b.HasIndex("direction");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("HW_Academy_RazorPages.Models.Student", b =>
                {
                    b.Property<int>("stud_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stud_id"));

                    b.Property<DateOnly>("birth_date")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("group")
                        .HasColumnType("int");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middle_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("photo")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("stud_id");

                    b.HasIndex("group");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HW_Academy_RazorPages.Models.Teacher", b =>
                {
                    b.Property<short>("teacher_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("teacher_id"));

                    b.Property<DateOnly>("birth_date")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middle_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("work_since")
                        .HasColumnType("date");

                    b.HasKey("teacher_id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("HW_Academy_RazorPages.Models.TeacherDisciplineRelation", b =>
                {
                    b.Property<short>("teacher")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("discipline")
                        .HasColumnType("SMALLINT");

                    b.HasKey("teacher", "discipline");

                    b.HasIndex("discipline");

                    b.ToTable("TeachersDisciplinesRelation");
                });

            modelBuilder.Entity("HW_Academy_RazorPages.Models.Group", b =>
                {
                    b.HasOne("HW_Academy_RazorPages.Models.Direction", "Direction")
                        .WithMany("Groups")
                        .HasForeignKey("direction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("HW_Academy_RazorPages.Models.Student", b =>
                {
                    b.HasOne("HW_Academy_RazorPages.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("group")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("HW_Academy_RazorPages.Models.TeacherDisciplineRelation", b =>
                {
                    b.HasOne("HW_Academy_RazorPages.Models.Discipline", "Discipline")
                        .WithMany("TeachersRelations")
                        .HasForeignKey("discipline")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HW_Academy_RazorPages.Models.Teacher", "Teacher")
                        .WithMany("DisciplinesRelations")
                        .HasForeignKey("teacher")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("HW_Academy_RazorPages.Models.Direction", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("HW_Academy_RazorPages.Models.Discipline", b =>
                {
                    b.Navigation("TeachersRelations");
                });

            modelBuilder.Entity("HW_Academy_RazorPages.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("HW_Academy_RazorPages.Models.Teacher", b =>
                {
                    b.Navigation("DisciplinesRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
